services:
  - type: web
    name: melonia-backend
    runtime: python
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    routes:
      - type: static
